package webindex

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"hash"
	"io"
	"io/fs"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"sync"

	"golang.org/x/mod/modfile"
)

const (
	// indexCacheFormatVersion invalidates persisted analysis whenever its inputs or representation change.
	indexCacheFormatVersion = 4
	// indexCacheMaximumSize bounds memory consumed by a corrupt or unexpectedly large cache entry.
	indexCacheMaximumSize = 64 << 20
	// indexCacheMagic separates this binary cache from generated JSON artifacts and future formats.
	indexCacheMagic = "goforj-webindex-cache-v4\n"
	// indexCacheEnvelopeLengthBytes stores three uint32 section lengths before cache payloads.
	indexCacheEnvelopeLengthBytes = 12
)

const (
	// indexCacheManifestArtifact identifies the canonical API index bytes independently of their destination path.
	indexCacheManifestArtifact = "manifest"
	// indexCacheDiagnosticsArtifact identifies the diagnostic projection bytes independently of their destination path.
	indexCacheDiagnosticsArtifact = "diagnostics"
	// indexCacheOpenAPIArtifact identifies the OpenAPI projection bytes independently of their destination path.
	indexCacheOpenAPIArtifact = "openapi"
)

// indexCacheRecord contains everything needed to return and publish one successful analysis without loading Go packages again.
type indexCacheRecord struct {
	Version      int                          `json:"version"`
	InputHash    string                       `json:"input_hash"`
	ManifestData []byte                       `json:"manifest_data"`
	Manifest     indexCacheManifestShape      `json:"manifest"`
	Artifacts    []indexCacheArtifact         `json:"artifacts"`
	TypedState   *typedSchemaIncrementalState `json:"-"`
}

// indexCacheEnvelope separates exact artifacts from incremental types so changed builds decode only the state they need.
type indexCacheEnvelope struct {
	inputHash string
	record    []byte
	typed     []byte
}

// indexCacheArtifact binds exact generated bytes to a stable role rather than a staging-directory path.
type indexCacheArtifact struct {
	Role string `json:"role"`
	Data []byte `json:"data"`
}

// indexCacheManifestShape retains runtime types and non-JSON state without duplicating canonical manifest values.
type indexCacheManifestShape struct {
	Operations []indexCacheOperationShape `json:"operations"`
	Schemas    [][]indexCacheValueShape   `json:"schemas"`
}

// indexCacheOperationShape retains omitted empty slices, schema runtime types, and private middleware provenance.
type indexCacheOperationShape struct {
	MiddlewarePresent           bool                     `json:"middleware_present,omitempty"`
	PathParamsPresent           bool                     `json:"path_params_present,omitempty"`
	QueryParamsPresent          bool                     `json:"query_params_present,omitempty"`
	HeadersPresent              bool                     `json:"headers_present,omitempty"`
	CookiesPresent              bool                     `json:"cookies_present,omitempty"`
	ResponsesPresent            bool                     `json:"responses_present,omitempty"`
	MetadataTagsPresent         bool                     `json:"metadata_tags_present,omitempty"`
	MiddlewareProvenancePresent bool                     `json:"middleware_provenance_present,omitempty"`
	MiddlewareProvenance        []middlewareProvenance   `json:"middleware_provenance"`
	Body                        []indexCacheValueShape   `json:"body,omitempty"`
	Responses                   [][]indexCacheValueShape `json:"responses"`
}

// indexCacheValueShape identifies one JSON-decoded value that needs its original concrete Go type restored.
type indexCacheValueShape struct {
	Path []indexCachePathSegment `json:"path,omitempty"`
	Kind string                  `json:"kind"`
}

// indexCachePathSegment navigates either one schema map key or one array index.
type indexCachePathSegment struct {
	Key   string `json:"key,omitempty"`
	Index int    `json:"index,omitempty"`
	Array bool   `json:"array,omitempty"`
}

const (
	indexCacheShapeAnySliceNil    = "any_slice_nil"
	indexCacheShapeFloat32        = "float32"
	indexCacheShapeFloat64        = "float64"
	indexCacheShapeInt            = "int"
	indexCacheShapeInt8           = "int8"
	indexCacheShapeInt16          = "int16"
	indexCacheShapeInt32          = "int32"
	indexCacheShapeInt64          = "int64"
	indexCacheShapeMapNil         = "map_nil"
	indexCacheShapeMapSlice       = "map_slice"
	indexCacheShapeMapSliceNil    = "map_slice_nil"
	indexCacheShapeStringSlice    = "string_slice"
	indexCacheShapeStringSliceNil = "string_slice_nil"
	indexCacheShapeUint           = "uint"
	indexCacheShapeUint8          = "uint8"
	indexCacheShapeUint16         = "uint16"
	indexCacheShapeUint32         = "uint32"
	indexCacheShapeUint64         = "uint64"
	indexCacheShapeUintptr        = "uintptr"
)

// indexCacheArtifactDestination binds a stable cache role to one run-specific publication path.
type indexCacheArtifactDestination struct {
	role string
	path string
}

// indexCacheSession retains the validated pre-run fingerprint so a successful miss can reject a source race before caching.
type indexCacheSession struct {
	path               string
	root               string
	inputHash          string
	dependencyIdentity string
	options            IndexOptions
	priorTypedState    *typedSchemaIncrementalState
	sourceFiles        []indexCacheFileDigest
	packageFiles       []indexCacheFileDigest
	inputFiles         []indexCacheInputFile
	goEnvironment      map[string]string
}

// indexCacheInputIdentities separates the exact artifact key from the stable dependency key used across source edits.
type indexCacheInputIdentities struct {
	exact         string
	dependency    string
	sourceFiles   []indexCacheFileDigest
	packageFiles  []indexCacheFileDigest
	inputFiles    []indexCacheInputFile
	goEnvironment map[string]string
}

// indexCacheOptionIdentity includes every caller choice that can alter returned or published contract bytes.
type indexCacheOptionIdentity struct {
	RouteCompositionPath string
	BuildTags            []string
	Strict               bool
	ManifestArtifact     bool
	DiagnosticsArtifact  bool
	OpenAPIArtifact      bool
	OpenAPI              OpenAPIOptions
}

// indexCacheFileDigest lets workers hash source bytes without introducing nondeterministic writes to the aggregate digest.
type indexCacheFileDigest struct {
	path     string
	data     []byte
	sum      [sha256.Size]byte
	metadata indexCacheSourceMetadata
}

// indexCacheInputFile retains optional configuration presence and bytes from the same read used by the cache fingerprint.
type indexCacheInputFile struct {
	path    string
	data    []byte
	present bool
}

// newIndexCacheSession validates the destination and computes an exact content fingerprint when this project shape is cacheable.
func newIndexCacheSession(ctx context.Context, root string, options IndexOptions, cachePath string) (*indexCacheSession, error) {
	if strings.TrimSpace(cachePath) == "" {
		return nil, nil
	}
	packageDriver := strings.TrimSpace(os.Getenv("GOPACKAGESDRIVER"))
	if options.SkipDir != nil || (packageDriver != "" && !strings.EqualFold(packageDriver, "off")) {
		return nil, nil
	}
	path := cachePath
	if !filepath.IsAbs(path) {
		path = filepath.Join(root, path)
	}
	path, err := filepath.Abs(path)
	if err != nil {
		return nil, fmt.Errorf("resolve API index cache path: %w", err)
	}
	path = filepath.Clean(path)
	if err := validateIndexCacheDestination(root, path, options); err != nil {
		return nil, err
	}
	identities, cacheable, err := indexCacheInputHashes(ctx, root, options)
	if err != nil {
		return nil, err
	}
	if !cacheable {
		return nil, nil
	}
	return &indexCacheSession{
		path:               path,
		root:               root,
		inputHash:          identities.exact,
		dependencyIdentity: identities.dependency,
		options:            options,
		sourceFiles:        identities.sourceFiles,
		packageFiles:       identities.packageFiles,
		inputFiles:         identities.inputFiles,
		goEnvironment:      identities.goEnvironment,
	}, nil
}

// validateIndexCacheDestination prevents a cache entry from replacing source, configuration, or public artifacts.
func validateIndexCacheDestination(root string, cachePath string, options IndexOptions) error {
	if indexCacheSourceExtension(filepath.Ext(cachePath)) {
		return fmt.Errorf("API index cache path %q must not use a source-file extension", cachePath)
	}
	if indexCachePathsEqual(filepath.Base(cachePath), ArtifactPublicationLockFilename) {
		return fmt.Errorf("API index cache path %q conflicts with the artifact publication lock", cachePath)
	}
	protected := []string{
		filepath.Join(root, "go.mod"),
		filepath.Join(root, "go.sum"),
		filepath.Join(root, ".env"),
	}
	protected = append(protected, indexCacheLocalModuleFiles(root)...)
	if compositionPath := resolvedIndexCacheCompositionPath(root, options.RouteCompositionPath); compositionPath != "" {
		protected = append(protected, compositionPath)
	}
	canonicalCachePath, err := canonicalIndexCachePath(cachePath)
	if err != nil {
		return fmt.Errorf("resolve API index cache path %q: %w", cachePath, err)
	}
	for _, inputPath := range protected {
		canonicalInputPath, err := canonicalIndexCachePath(inputPath)
		if err != nil {
			return fmt.Errorf("resolve API index input path %q: %w", inputPath, err)
		}
		if indexCachePathsEqual(canonicalInputPath, canonicalCachePath) {
			return fmt.Errorf("API index cache path %q conflicts with an indexing input", cachePath)
		}
	}
	for _, artifactPath := range []string{options.OutPath, options.DiagnosticsPath, options.OpenAPIPath} {
		if strings.TrimSpace(artifactPath) == "" {
			continue
		}
		absolute, err := filepath.Abs(artifactPath)
		if err != nil {
			return fmt.Errorf("resolve API index artifact path %q: %w", artifactPath, err)
		}
		canonicalArtifactPath, err := canonicalIndexCachePath(absolute)
		if err != nil {
			return fmt.Errorf("resolve API index artifact path %q: %w", artifactPath, err)
		}
		if indexCachePathsEqual(canonicalArtifactPath, canonicalCachePath) {
			return fmt.Errorf("API index cache path %q conflicts with a generated artifact", cachePath)
		}
	}
	if info, err := os.Lstat(cachePath); err == nil && !info.Mode().IsRegular() {
		return fmt.Errorf("API index cache path %q is not a regular file", cachePath)
	} else if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("inspect API index cache path %q: %w", cachePath, err)
	}
	return nil
}

// indexCacheLocalModuleFiles returns replacement-module metadata only when the complete local module set is valid.
func indexCacheLocalModuleFiles(root string) []string {
	moduleData, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return nil
	}
	moduleFile, err := modfile.Parse(filepath.Join(root, "go.mod"), moduleData, nil)
	if err != nil {
		return nil
	}
	moduleRoots, cacheable := indexCacheModuleRoots(root, moduleFile)
	if !cacheable {
		return nil
	}
	paths := make([]string, 0, len(moduleRoots)*2)
	for _, moduleRoot := range moduleRoots {
		paths = append(paths, filepath.Join(moduleRoot, "go.mod"), filepath.Join(moduleRoot, "go.sum"))
	}
	return paths
}

// canonicalIndexCachePath resolves existing symlinked ancestors before comparing destinations that may not exist yet.
func canonicalIndexCachePath(path string) (string, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	candidate := filepath.Clean(absolute)
	suffix := make([]string, 0)
	for {
		if _, err := os.Lstat(candidate); err == nil {
			resolved, err := filepath.EvalSymlinks(candidate)
			if err != nil {
				return "", err
			}
			for index := len(suffix) - 1; index >= 0; index-- {
				resolved = filepath.Join(resolved, suffix[index])
			}
			return filepath.Clean(resolved), nil
		} else if !os.IsNotExist(err) {
			return "", err
		}
		parent := filepath.Dir(candidate)
		if parent == candidate {
			return candidate, nil
		}
		suffix = append(suffix, filepath.Base(candidate))
		candidate = parent
	}
}

// load returns a verified cache record remapped to this run's artifact destinations.
func (cache *indexCacheSession) load(ctx context.Context) (Manifest, []encodedJSONArtifact, bool) {
	if cache == nil {
		return Manifest{}, nil, false
	}
	if ctx == nil {
		ctx = context.Background()
	}
	if ctx.Err() != nil {
		return Manifest{}, nil, false
	}
	record, ok := readDecodedIndexCacheRecord(cache.path, cache.inputHash)
	if !ok || record.Version != indexCacheFormatVersion {
		return Manifest{}, nil, false
	}
	cache.priorTypedState = record.TypedState
	if record.InputHash != cache.inputHash {
		return Manifest{}, nil, false
	}
	manifest, ok := restoreIndexCacheManifest(record)
	if !ok {
		return Manifest{}, nil, false
	}
	artifacts, ok := cachedIndexArtifacts(record, manifest, cache.options)
	if !ok {
		return Manifest{}, nil, false
	}
	return manifest, artifacts, true
}

// inputStillCurrent closes the source-change window between the initial fingerprint and output or cache publication.
func (cache *indexCacheSession) inputStillCurrent(ctx context.Context) bool {
	if cache == nil || ctx == nil || ctx.Err() != nil {
		return false
	}
	currentHash, cacheable, err := indexCacheInputHash(ctx, cache.root, cache.options)
	return err == nil && cacheable && currentHash == cache.inputHash
}

// readIndexCacheData rejects non-regular and oversized entries before allocating for their complete contents.
func readIndexCacheData(path string) ([]byte, bool) {
	file, err := os.Open(path)
	if err != nil {
		return nil, false
	}
	defer file.Close()
	info, err := file.Stat()
	if err != nil || !info.Mode().IsRegular() || info.Size() > indexCacheMaximumSize {
		return nil, false
	}
	data, err := io.ReadAll(io.LimitReader(file, indexCacheMaximumSize+1))
	if err != nil || len(data) > indexCacheMaximumSize {
		return nil, false
	}
	return data, true
}

// encodedArtifact prepares cache bytes for the same locked publication transaction as generated outputs.
func (cache *indexCacheSession) encodedArtifact(manifest Manifest, artifacts []encodedJSONArtifact, typedState *typedSchemaIncrementalState) (encodedJSONArtifact, bool) {
	if cache == nil {
		return encodedJSONArtifact{}, false
	}
	recordArtifacts, ok := cacheRecordArtifacts(cache.options, artifacts)
	if !ok {
		return encodedJSONArtifact{}, false
	}
	var manifestData []byte
	for index, artifact := range recordArtifacts {
		if artifact.Role == indexCacheManifestArtifact {
			manifestData = artifacts[index].data
			break
		}
	}
	if manifestData == nil {
		manifestArtifacts, err := encodeJSONArtifacts([]jsonArtifact{{path: "manifest", value: manifest}})
		if err != nil {
			return encodedJSONArtifact{}, false
		}
		manifestData = manifestArtifacts[0].data
	}
	manifestShape, ok := captureIndexCacheManifestShape(manifest)
	if !ok {
		return encodedJSONArtifact{}, false
	}
	record := indexCacheRecord{
		Version:      indexCacheFormatVersion,
		InputHash:    cache.inputHash,
		ManifestData: manifestData,
		Manifest:     manifestShape,
		Artifacts:    recordArtifacts,
		TypedState:   typedState,
	}
	if _, ok := restoreIndexCacheManifest(record); !ok {
		return encodedJSONArtifact{}, false
	}
	data, err := encodeIndexCacheRecord(record)
	if err != nil || len(data) > indexCacheMaximumSize {
		return encodedJSONArtifact{}, false
	}
	rememberDecodedIndexCacheRecord(cache.path, data, record, nil)
	return encodedJSONArtifact{path: cache.path, data: data}, true
}

// cachedIndexArtifacts validates every cached JSON role and maps it to the paths requested by the current run.
func cachedIndexArtifacts(record indexCacheRecord, manifest Manifest, options IndexOptions) ([]encodedJSONArtifact, bool) {
	destinations := indexCacheArtifactDestinations(options)
	if len(record.Artifacts) != len(destinations) {
		return nil, false
	}
	byRole := make(map[string][]byte, len(record.Artifacts))
	for _, artifact := range record.Artifacts {
		data := artifact.Data
		if artifact.Role == indexCacheManifestArtifact && len(data) == 0 {
			data = record.ManifestData
		}
		if artifact.Role == "" || !json.Valid(data) {
			return nil, false
		}
		if _, exists := byRole[artifact.Role]; exists {
			return nil, false
		}
		byRole[artifact.Role] = data
	}
	encoded := make([]encodedJSONArtifact, 0, len(destinations))
	for _, destination := range destinations {
		data, exists := byRole[destination.role]
		if !exists {
			return nil, false
		}
		encoded = append(encoded, encodedJSONArtifact{path: destination.path, data: append([]byte(nil), data...)})
	}
	if cached, exists := byRole[indexCacheManifestArtifact]; exists && !bytes.Equal(cached, record.ManifestData) {
		return nil, false
	}
	diagnosticsBytes, err := encodeJSONArtifacts([]jsonArtifact{{path: "diagnostics", value: manifest.Diagnostics}})
	if err != nil {
		return nil, false
	}
	if cached, exists := byRole[indexCacheDiagnosticsArtifact]; exists && !bytes.Equal(cached, diagnosticsBytes[0].data) {
		return nil, false
	}
	return encoded, true
}

// restoreIndexCacheManifest rebuilds the exact public runtime shape while retaining source-only middleware provenance.
func restoreIndexCacheManifest(record indexCacheRecord) (Manifest, bool) {
	if !json.Valid(record.ManifestData) {
		return Manifest{}, false
	}
	decoder := json.NewDecoder(bytes.NewReader(record.ManifestData))
	decoder.UseNumber()
	var manifest Manifest
	if err := decoder.Decode(&manifest); err != nil || manifest.Version != ManifestVersion || len(record.Manifest.Operations) != len(manifest.Operations) || len(record.Manifest.Schemas) != len(manifest.Schemas) {
		return Manifest{}, false
	}
	for index := range manifest.Operations {
		operation := &manifest.Operations[index]
		shape := record.Manifest.Operations[index]
		var ok bool
		if operation.Middleware, ok = restoreIndexCacheSlicePresence(operation.Middleware, shape.MiddlewarePresent); !ok {
			return Manifest{}, false
		}
		if operation.Inputs.PathParams, ok = restoreIndexCacheSlicePresence(operation.Inputs.PathParams, shape.PathParamsPresent); !ok {
			return Manifest{}, false
		}
		if operation.Inputs.QueryParams, ok = restoreIndexCacheSlicePresence(operation.Inputs.QueryParams, shape.QueryParamsPresent); !ok {
			return Manifest{}, false
		}
		if operation.Inputs.Headers, ok = restoreIndexCacheSlicePresence(operation.Inputs.Headers, shape.HeadersPresent); !ok {
			return Manifest{}, false
		}
		if operation.Inputs.Cookies, ok = restoreIndexCacheSlicePresence(operation.Inputs.Cookies, shape.CookiesPresent); !ok {
			return Manifest{}, false
		}
		if operation.Outputs.Responses, ok = restoreIndexCacheSlicePresence(operation.Outputs.Responses, shape.ResponsesPresent); !ok || len(shape.Responses) != len(operation.Outputs.Responses) {
			return Manifest{}, false
		}
		if operation.Metadata != nil {
			if operation.Metadata.Tags, ok = restoreIndexCacheSlicePresence(operation.Metadata.Tags, shape.MetadataTagsPresent); !ok {
				return Manifest{}, false
			}
		} else if shape.MetadataTagsPresent {
			return Manifest{}, false
		}
		if operation.middlewareProvenance, ok = restoreIndexCacheSlicePresence(shape.MiddlewareProvenance, shape.MiddlewareProvenancePresent); !ok {
			return Manifest{}, false
		}
		if operation.Inputs.Body != nil {
			if operation.Inputs.Body.Schema, ok = restoreIndexCacheValueShape(operation.Inputs.Body.Schema, shape.Body); !ok {
				return Manifest{}, false
			}
		} else if len(shape.Body) > 0 {
			return Manifest{}, false
		}
		for responseIndex := range operation.Outputs.Responses {
			if operation.Outputs.Responses[responseIndex].Schema, ok = restoreIndexCacheValueShape(operation.Outputs.Responses[responseIndex].Schema, shape.Responses[responseIndex]); !ok {
				return Manifest{}, false
			}
		}
	}
	for index := range manifest.Schemas {
		definition, ok := restoreIndexCacheValueShape(manifest.Schemas[index].Definition, record.Manifest.Schemas[index])
		if !ok {
			return Manifest{}, false
		}
		manifest.Schemas[index].Definition = definition
	}
	encoded, err := encodeJSONArtifacts([]jsonArtifact{{path: "manifest", value: manifest}})
	if err != nil || !bytes.Equal(encoded[0].data, record.ManifestData) {
		return Manifest{}, false
	}
	return manifest, true
}

// captureIndexCacheManifestShape records only the runtime details canonical JSON cannot preserve by itself.
func captureIndexCacheManifestShape(manifest Manifest) (indexCacheManifestShape, bool) {
	shape := indexCacheManifestShape{
		Operations: make([]indexCacheOperationShape, len(manifest.Operations)),
		Schemas:    make([][]indexCacheValueShape, len(manifest.Schemas)),
	}
	for index := range manifest.Operations {
		operation := manifest.Operations[index]
		current := &shape.Operations[index]
		current.MiddlewarePresent = operation.Middleware != nil
		current.PathParamsPresent = operation.Inputs.PathParams != nil
		current.QueryParamsPresent = operation.Inputs.QueryParams != nil
		current.HeadersPresent = operation.Inputs.Headers != nil
		current.CookiesPresent = operation.Inputs.Cookies != nil
		current.ResponsesPresent = operation.Outputs.Responses != nil
		current.MetadataTagsPresent = operation.Metadata != nil && operation.Metadata.Tags != nil
		current.MiddlewareProvenancePresent = operation.middlewareProvenance != nil
		current.MiddlewareProvenance = append([]middlewareProvenance(nil), operation.middlewareProvenance...)
		var ok bool
		if operation.Inputs.Body != nil {
			current.Body, ok = captureIndexCacheValueShape(operation.Inputs.Body.Schema)
			if !ok {
				return indexCacheManifestShape{}, false
			}
		}
		current.Responses = make([][]indexCacheValueShape, len(operation.Outputs.Responses))
		for responseIndex := range operation.Outputs.Responses {
			current.Responses[responseIndex], ok = captureIndexCacheValueShape(operation.Outputs.Responses[responseIndex].Schema)
			if !ok {
				return indexCacheManifestShape{}, false
			}
		}
	}
	for index := range manifest.Schemas {
		var ok bool
		shape.Schemas[index], ok = captureIndexCacheValueShape(manifest.Schemas[index].Definition)
		if !ok {
			return indexCacheManifestShape{}, false
		}
	}
	return shape, true
}

// captureIndexCacheValueShape records concrete schema value types that decoding canonical JSON cannot recover.
func captureIndexCacheValueShape(value any) ([]indexCacheValueShape, bool) {
	shapes := make([]indexCacheValueShape, 0)
	if !appendIndexCacheValueShape(value, nil, &shapes) {
		return nil, false
	}
	return shapes, true
}

// appendIndexCacheValueShape walks one generated schema using deterministic map-key order.
func appendIndexCacheValueShape(value any, path []indexCachePathSegment, shapes *[]indexCacheValueShape) bool {
	appendShape := func(kind string) {
		*shapes = append(*shapes, indexCacheValueShape{
			Path: append([]indexCachePathSegment(nil), path...),
			Kind: kind,
		})
	}
	appendArrayPath := func(index int) []indexCachePathSegment {
		return append(append([]indexCachePathSegment(nil), path...), indexCachePathSegment{Index: index, Array: true})
	}
	switch typed := value.(type) {
	case nil, bool, string:
		return true
	case json.Number:
		_, err := json.Marshal(typed)
		return err == nil
	case map[string]any:
		if typed == nil {
			appendShape(indexCacheShapeMapNil)
			return true
		}
		keys := make([]string, 0, len(typed))
		for key := range typed {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			childPath := append(append([]indexCachePathSegment(nil), path...), indexCachePathSegment{Key: key})
			if !appendIndexCacheValueShape(typed[key], childPath, shapes) {
				return false
			}
		}
		return true
	case []any:
		if typed == nil {
			appendShape(indexCacheShapeAnySliceNil)
			return true
		}
		for index, child := range typed {
			if !appendIndexCacheValueShape(child, appendArrayPath(index), shapes) {
				return false
			}
		}
		return true
	case []string:
		if typed == nil {
			appendShape(indexCacheShapeStringSliceNil)
		} else {
			appendShape(indexCacheShapeStringSlice)
		}
		return true
	case []map[string]any:
		if typed == nil {
			appendShape(indexCacheShapeMapSliceNil)
			return true
		}
		for index, child := range typed {
			if !appendIndexCacheValueShape(child, appendArrayPath(index), shapes) {
				return false
			}
		}
		// Container conversion follows child restoration because child paths navigate the decoded []any value.
		appendShape(indexCacheShapeMapSlice)
		return true
	case int:
		appendShape(indexCacheShapeInt)
	case int8:
		appendShape(indexCacheShapeInt8)
	case int16:
		appendShape(indexCacheShapeInt16)
	case int32:
		appendShape(indexCacheShapeInt32)
	case int64:
		appendShape(indexCacheShapeInt64)
	case uint:
		appendShape(indexCacheShapeUint)
	case uint8:
		appendShape(indexCacheShapeUint8)
	case uint16:
		appendShape(indexCacheShapeUint16)
	case uint32:
		appendShape(indexCacheShapeUint32)
	case uint64:
		appendShape(indexCacheShapeUint64)
	case uintptr:
		appendShape(indexCacheShapeUintptr)
	case float32:
		if math.IsInf(float64(typed), 0) || math.IsNaN(float64(typed)) {
			return false
		}
		appendShape(indexCacheShapeFloat32)
	case float64:
		if math.IsInf(typed, 0) || math.IsNaN(typed) {
			return false
		}
		appendShape(indexCacheShapeFloat64)
	default:
		return false
	}
	return true
}

// restoreIndexCacheValueShape reapplies the concrete types captured alongside canonical manifest JSON.
func restoreIndexCacheValueShape(value any, shapes []indexCacheValueShape) (any, bool) {
	var ok bool
	for _, shape := range shapes {
		value, ok = restoreIndexCacheValueAtPath(value, shape.Path, shape.Kind)
		if !ok {
			return nil, false
		}
	}
	return value, true
}

// restoreIndexCacheValueAtPath replaces one decoded schema value after validating every path segment.
func restoreIndexCacheValueAtPath(value any, path []indexCachePathSegment, kind string) (any, bool) {
	if len(path) == 0 {
		return restoreIndexCacheValueKind(value, kind)
	}
	segment := path[0]
	if segment.Array {
		values, ok := value.([]any)
		if !ok || segment.Index < 0 || segment.Index >= len(values) {
			return nil, false
		}
		restored, ok := restoreIndexCacheValueAtPath(values[segment.Index], path[1:], kind)
		if !ok {
			return nil, false
		}
		values[segment.Index] = restored
		return values, true
	}
	values, ok := value.(map[string]any)
	if !ok {
		return nil, false
	}
	child, exists := values[segment.Key]
	if !exists {
		return nil, false
	}
	restored, ok := restoreIndexCacheValueAtPath(child, path[1:], kind)
	if !ok {
		return nil, false
	}
	values[segment.Key] = restored
	return values, true
}

// restoreIndexCacheValueKind converts one JSON-decoded value into its captured concrete Go type.
func restoreIndexCacheValueKind(value any, kind string) (any, bool) {
	number, numberOK := value.(json.Number)
	switch kind {
	case indexCacheShapeAnySliceNil:
		if value != nil {
			return nil, false
		}
		return []any(nil), true
	case indexCacheShapeMapNil:
		if value != nil {
			return nil, false
		}
		return map[string]any(nil), true
	case indexCacheShapeMapSliceNil:
		if value != nil {
			return nil, false
		}
		return []map[string]any(nil), true
	case indexCacheShapeStringSliceNil:
		if value != nil {
			return nil, false
		}
		return []string(nil), true
	case indexCacheShapeMapSlice:
		values, ok := value.([]any)
		if !ok {
			return nil, false
		}
		restored := make([]map[string]any, len(values))
		for index, item := range values {
			object, ok := item.(map[string]any)
			if !ok {
				return nil, false
			}
			restored[index] = object
		}
		return restored, true
	case indexCacheShapeStringSlice:
		values, ok := value.([]any)
		if !ok {
			return nil, false
		}
		restored := make([]string, len(values))
		for index, item := range values {
			text, ok := item.(string)
			if !ok {
				return nil, false
			}
			restored[index] = text
		}
		return restored, true
	case indexCacheShapeInt:
		parsed, err := strconv.ParseInt(number.String(), 10, strconv.IntSize)
		return int(parsed), numberOK && err == nil
	case indexCacheShapeInt8:
		parsed, err := strconv.ParseInt(number.String(), 10, 8)
		return int8(parsed), numberOK && err == nil
	case indexCacheShapeInt16:
		parsed, err := strconv.ParseInt(number.String(), 10, 16)
		return int16(parsed), numberOK && err == nil
	case indexCacheShapeInt32:
		parsed, err := strconv.ParseInt(number.String(), 10, 32)
		return int32(parsed), numberOK && err == nil
	case indexCacheShapeInt64:
		parsed, err := strconv.ParseInt(number.String(), 10, 64)
		return parsed, numberOK && err == nil
	case indexCacheShapeUint:
		parsed, err := strconv.ParseUint(number.String(), 10, strconv.IntSize)
		return uint(parsed), numberOK && err == nil
	case indexCacheShapeUint8:
		parsed, err := strconv.ParseUint(number.String(), 10, 8)
		return uint8(parsed), numberOK && err == nil
	case indexCacheShapeUint16:
		parsed, err := strconv.ParseUint(number.String(), 10, 16)
		return uint16(parsed), numberOK && err == nil
	case indexCacheShapeUint32:
		parsed, err := strconv.ParseUint(number.String(), 10, 32)
		return uint32(parsed), numberOK && err == nil
	case indexCacheShapeUint64:
		parsed, err := strconv.ParseUint(number.String(), 10, 64)
		return parsed, numberOK && err == nil
	case indexCacheShapeUintptr:
		parsed, err := strconv.ParseUint(number.String(), 10, strconv.IntSize)
		return uintptr(parsed), numberOK && err == nil
	case indexCacheShapeFloat32:
		parsed, err := strconv.ParseFloat(number.String(), 32)
		return float32(parsed), numberOK && err == nil && !math.IsInf(parsed, 0) && !math.IsNaN(parsed)
	case indexCacheShapeFloat64:
		parsed, err := strconv.ParseFloat(number.String(), 64)
		return parsed, numberOK && err == nil && !math.IsInf(parsed, 0) && !math.IsNaN(parsed)
	default:
		return nil, false
	}
}

// restoreIndexCacheSlicePresence recovers empty non-nil slices omitted from canonical manifest JSON.
func restoreIndexCacheSlicePresence[T any](value []T, present bool) ([]T, bool) {
	if present {
		if value == nil {
			return make([]T, 0), true
		}
		return value, true
	}
	if value != nil {
		return nil, false
	}
	return nil, true
}

// cacheRecordArtifacts converts path-bound encoded outputs into stable roles for reuse with GoForj staging directories.
func cacheRecordArtifacts(options IndexOptions, encoded []encodedJSONArtifact) ([]indexCacheArtifact, bool) {
	destinations := indexCacheArtifactDestinations(options)
	if len(destinations) != len(encoded) {
		return nil, false
	}
	artifacts := make([]indexCacheArtifact, 0, len(encoded))
	for index, artifact := range encoded {
		if filepath.Clean(artifact.path) != filepath.Clean(destinations[index].path) || !json.Valid(artifact.data) {
			return nil, false
		}
		data := artifact.data
		if destinations[index].role == indexCacheManifestArtifact {
			data = nil
		}
		artifacts = append(artifacts, indexCacheArtifact{Role: destinations[index].role, Data: data})
	}
	return artifacts, true
}

// indexCacheArtifactDestinations returns stable roles and their current path in the same order used by Run.
func indexCacheArtifactDestinations(options IndexOptions) []indexCacheArtifactDestination {
	destinations := make([]indexCacheArtifactDestination, 0, 3)
	if options.OutPath != "" {
		destinations = append(destinations, indexCacheArtifactDestination{role: indexCacheManifestArtifact, path: options.OutPath})
	}
	if options.DiagnosticsPath != "" {
		destinations = append(destinations, indexCacheArtifactDestination{role: indexCacheDiagnosticsArtifact, path: options.DiagnosticsPath})
	}
	if options.OpenAPIPath != "" {
		destinations = append(destinations, indexCacheArtifactDestination{role: indexCacheOpenAPIArtifact, path: options.OpenAPIPath})
	}
	return destinations
}

// encodeIndexCacheRecord frames independently decodable exact and incremental payloads behind one checksum.
func encodeIndexCacheRecord(record indexCacheRecord) ([]byte, error) {
	exactPayload, err := json.Marshal(record)
	if err != nil {
		return nil, fmt.Errorf("encode API index cache: %w", err)
	}
	var typedPayload []byte
	if record.TypedState != nil {
		typedPayload, err = encodeTypedSchemaIncrementalState(record.TypedState)
		if err != nil {
			return nil, err
		}
	}
	return frameIndexCacheEnvelope(record.InputHash, exactPayload, typedPayload)
}

// frameIndexCacheEnvelope builds deterministic framing around already encoded sections.
func frameIndexCacheEnvelope(inputHash string, exactPayload []byte, typedPayload []byte) ([]byte, error) {
	if inputHash == "" || len(exactPayload) == 0 || uint64(len(inputHash)) > uint64(^uint32(0)) || uint64(len(exactPayload)) > uint64(^uint32(0)) || uint64(len(typedPayload)) > uint64(^uint32(0)) {
		return nil, fmt.Errorf("encode API index cache envelope: invalid section length")
	}
	headerLength := len(indexCacheMagic) + sha256.Size*2 + 1
	bodyLengthValue := uint64(indexCacheEnvelopeLengthBytes) + uint64(len(inputHash)) + uint64(len(exactPayload)) + uint64(len(typedPayload))
	if bodyLengthValue > uint64(indexCacheMaximumSize-headerLength) {
		return nil, fmt.Errorf("encode API index cache envelope: cache exceeds %d bytes", indexCacheMaximumSize)
	}
	bodyLength := int(bodyLengthValue)
	data := make([]byte, headerLength+bodyLength)
	copy(data, indexCacheMagic)
	data[len(indexCacheMagic)+sha256.Size*2] = '\n'
	body := data[headerLength:]
	binary.BigEndian.PutUint32(body[0:4], uint32(len(inputHash)))
	binary.BigEndian.PutUint32(body[4:8], uint32(len(exactPayload)))
	binary.BigEndian.PutUint32(body[8:12], uint32(len(typedPayload)))
	offset := indexCacheEnvelopeLengthBytes
	offset += copy(body[offset:], inputHash)
	offset += copy(body[offset:], exactPayload)
	copy(body[offset:], typedPayload)
	sum := sha256.Sum256(body)
	hex.Encode(data[len(indexCacheMagic):len(indexCacheMagic)+sha256.Size*2], sum[:])
	return data, nil
}

// decodeIndexCacheRecord verifies framing and content before exposing a persisted manifest.
func decodeIndexCacheRecord(data []byte) (indexCacheRecord, bool) {
	envelope, ok := decodeIndexCacheEnvelope(data)
	if !ok {
		return indexCacheRecord{}, false
	}
	record, ok := decodeIndexCacheExactRecord(envelope.record, envelope.inputHash)
	if !ok {
		return indexCacheRecord{}, false
	}
	typedState, ok := decodeIndexCacheTypedState(envelope.typed)
	if !ok {
		return indexCacheRecord{}, false
	}
	record.TypedState = typedState
	return record, true
}

// decodeIndexCacheEnvelope validates framing and exposes bounded section slices without decoding unused payloads.
func decodeIndexCacheEnvelope(data []byte) (indexCacheEnvelope, bool) {
	headerLength := len(indexCacheMagic) + sha256.Size*2 + 1
	if len(data) < headerLength+indexCacheEnvelopeLengthBytes || len(data) > indexCacheMaximumSize || !bytes.HasPrefix(data, []byte(indexCacheMagic)) {
		return indexCacheEnvelope{}, false
	}
	checksumStart := len(indexCacheMagic)
	checksumEnd := checksumStart + sha256.Size*2
	if data[checksumEnd] != '\n' {
		return indexCacheEnvelope{}, false
	}
	expected, err := hex.DecodeString(string(data[checksumStart:checksumEnd]))
	if err != nil {
		return indexCacheEnvelope{}, false
	}
	body := data[headerLength:]
	actual := sha256.Sum256(body)
	if !bytes.Equal(expected, actual[:]) {
		return indexCacheEnvelope{}, false
	}
	inputHashLength := uint64(binary.BigEndian.Uint32(body[0:4]))
	recordLength := uint64(binary.BigEndian.Uint32(body[4:8]))
	typedLength := uint64(binary.BigEndian.Uint32(body[8:12]))
	payloadLength := inputHashLength + recordLength + typedLength
	if inputHashLength == 0 || recordLength == 0 || payloadLength != uint64(len(body)-indexCacheEnvelopeLengthBytes) {
		return indexCacheEnvelope{}, false
	}
	offset := uint64(indexCacheEnvelopeLengthBytes)
	inputHashEnd := offset + inputHashLength
	recordEnd := inputHashEnd + recordLength
	typedEnd := recordEnd + typedLength
	return indexCacheEnvelope{
		inputHash: string(body[offset:inputHashEnd]),
		record:    body[inputHashEnd:recordEnd],
		typed:     body[recordEnd:typedEnd],
	}, true
}

// decodeIndexCacheExactRecord validates canonical artifact JSON independently of the incremental state.
func decodeIndexCacheExactRecord(payload []byte, inputHash string) (indexCacheRecord, bool) {
	var record indexCacheRecord
	decoder := json.NewDecoder(bytes.NewReader(payload))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&record); err != nil || record.InputHash != inputHash {
		return indexCacheRecord{}, false
	}
	canonical, err := json.Marshal(record)
	if err != nil || !bytes.Equal(canonical, payload) {
		return indexCacheRecord{}, false
	}
	return record, true
}

// decodeIndexCacheTypedState decodes only the state needed after an exact source miss.
func decodeIndexCacheTypedState(payload []byte) (*typedSchemaIncrementalState, bool) {
	if len(payload) == 0 {
		return nil, true
	}
	return decodeTypedSchemaIncrementalState(payload)
}

// indexCacheInputHash fingerprints exact source bytes, module selection, build environment, and projection options.
func indexCacheInputHash(ctx context.Context, root string, options IndexOptions) (string, bool, error) {
	identities, cacheable, err := indexCacheInputHashes(ctx, root, options)
	return identities.exact, cacheable, err
}

// indexCacheInputHashes computes exact artifact and stable dependency identities from one environment and source scan.
func indexCacheInputHashes(ctx context.Context, root string, options IndexOptions) (indexCacheInputIdentities, bool, error) {
	if err := ctx.Err(); err != nil {
		return indexCacheInputIdentities{}, false, err
	}
	goEnvironment, environmentValues, err := indexCacheGoEnvironment(ctx, root)
	if err != nil {
		if contextErr := ctx.Err(); contextErr != nil {
			return indexCacheInputIdentities{}, false, contextErr
		}
		return indexCacheInputIdentities{}, false, nil
	}
	if strings.EqualFold(strings.TrimSpace(environmentValues["GO111MODULE"]), "off") {
		return indexCacheInputIdentities{}, false, nil
	}
	if !indexCacheGoFlagsCovered(environmentValues["GOFLAGS"]) {
		return indexCacheInputIdentities{}, false, nil
	}
	if workspace := strings.TrimSpace(environmentValues["GOWORK"]); workspace != "" && !strings.EqualFold(workspace, "off") {
		return indexCacheInputIdentities{}, false, nil
	}
	if info, statErr := os.Stat(filepath.Join(root, "vendor")); statErr == nil && info.IsDir() {
		return indexCacheInputIdentities{}, false, nil
	} else if statErr != nil && !os.IsNotExist(statErr) {
		return indexCacheInputIdentities{}, false, nil
	}

	rootModuleInput, err := readIndexCacheInputFile(filepath.Join(root, "go.mod"))
	if err != nil || !rootModuleInput.present {
		return indexCacheInputIdentities{}, false, nil
	}
	moduleFile, err := modfile.Parse(rootModuleInput.path, rootModuleInput.data, nil)
	if err != nil {
		return indexCacheInputIdentities{}, false, nil
	}
	optionData, err := json.Marshal(indexCacheOptionIdentity{
		RouteCompositionPath: normalizedIndexCacheCompositionPath(root, options.RouteCompositionPath),
		BuildTags:            normalizeSourceBuildTags(options.BuildTags),
		Strict:               options.Strict,
		ManifestArtifact:     options.OutPath != "",
		DiagnosticsArtifact:  options.DiagnosticsPath != "",
		OpenAPIArtifact:      options.OpenAPIPath != "",
		OpenAPI:              options.OpenAPI,
	})
	if err != nil {
		return indexCacheInputIdentities{}, false, nil
	}

	digest := sha256.New()
	writeIndexCacheHashString(digest, "goforj-webindex-analysis-v1")
	writeIndexCacheHashString(digest, ManifestVersion)
	writeIndexCacheHashString(digest, runtime.Version())
	writeIndexCacheHashString(digest, filepath.Clean(root))
	writeIndexCacheHashBytes(digest, goEnvironment)
	writeIndexCacheHashBytes(digest, optionData)
	dependencyDigest := sha256.New()
	writeIndexCacheHashString(dependencyDigest, "goforj-webindex-typed-dependencies-v1")
	writeIndexCacheHashString(dependencyDigest, runtime.Version())
	writeIndexCacheHashString(dependencyDigest, filepath.Clean(root))
	writeIndexCacheHashBytes(dependencyDigest, goEnvironment)
	buildTags, err := json.Marshal(normalizeSourceBuildTags(options.BuildTags))
	if err != nil {
		return indexCacheInputIdentities{}, false, nil
	}
	writeIndexCacheHashBytes(dependencyDigest, buildTags)

	moduleRoots, cacheable := indexCacheModuleRoots(root, moduleFile)
	if !cacheable {
		return indexCacheInputIdentities{}, false, nil
	}
	inputFiles := make([]indexCacheInputFile, 0, len(moduleRoots)*2+2)
	allFileDigests := make([]indexCacheFileDigest, 0, 128)
	var rootFileDigests []indexCacheFileDigest
	for _, moduleRoot := range moduleRoots {
		writeIndexCacheHashString(digest, moduleRoot)
		writeIndexCacheHashString(dependencyDigest, moduleRoot)
		moduleInput := rootModuleInput
		if filepath.Clean(moduleRoot) != filepath.Clean(root) {
			moduleInput, err = readIndexCacheInputFile(filepath.Join(moduleRoot, "go.mod"))
			if err != nil || !moduleInput.present {
				return indexCacheInputIdentities{}, false, nil
			}
		}
		sumInput, err := readIndexCacheInputFile(filepath.Join(moduleRoot, "go.sum"))
		if err != nil {
			return indexCacheInputIdentities{}, false, nil
		}
		inputFiles = append(inputFiles, moduleInput, sumInput)
		writeIndexCacheInputFileState(digest, moduleInput)
		writeIndexCacheInputFileState(digest, sumInput)
		writeIndexCacheInputFileState(dependencyDigest, moduleInput)
		writeIndexCacheInputFileState(dependencyDigest, sumInput)
		paths, err := indexCacheSourcePaths(ctx, moduleRoot)
		if err != nil {
			if contextErr := ctx.Err(); contextErr != nil {
				return indexCacheInputIdentities{}, false, contextErr
			}
			return indexCacheInputIdentities{}, false, nil
		}
		fileDigests, err := indexCacheFileDigests(ctx, paths)
		if err != nil {
			if contextErr := ctx.Err(); contextErr != nil {
				return indexCacheInputIdentities{}, false, contextErr
			}
			return indexCacheInputIdentities{}, false, nil
		}
		if filepath.Clean(moduleRoot) == filepath.Clean(root) {
			rootFileDigests = append([]indexCacheFileDigest(nil), fileDigests...)
		}
		allFileDigests = append(allFileDigests, fileDigests...)
		for _, fileDigest := range fileDigests {
			writeIndexCacheHashString(digest, fileDigest.path)
			writeIndexCacheHashBytes(digest, fileDigest.sum[:])
		}
	}
	if !indexCacheFileDigestsCovered(allFileDigests) {
		return indexCacheInputIdentities{}, false, nil
	}
	if !indexCacheLocalImportsCovered(root, moduleFile, allFileDigests, inputFiles) {
		return indexCacheInputIdentities{}, false, nil
	}
	embedCacheable, err := writeIndexCacheEmbedStructure(ctx, digest, allFileDigests)
	if err != nil {
		if contextErr := ctx.Err(); contextErr != nil {
			return indexCacheInputIdentities{}, false, contextErr
		}
		return indexCacheInputIdentities{}, false, nil
	}
	if !embedCacheable {
		return indexCacheInputIdentities{}, false, nil
	}
	environmentInput, err := readIndexCacheInputFile(filepath.Join(root, ".env"))
	if err != nil {
		return indexCacheInputIdentities{}, false, nil
	}
	inputFiles = append(inputFiles, environmentInput)
	writeIndexCacheInputFileState(digest, environmentInput)
	if compositionPath := resolvedIndexCacheCompositionPath(root, options.RouteCompositionPath); compositionPath != "" {
		compositionInput, err := readIndexCacheInputFile(compositionPath)
		if err != nil {
			return indexCacheInputIdentities{}, false, nil
		}
		inputFiles = append(inputFiles, compositionInput)
		writeIndexCacheInputFileState(digest, compositionInput)
	}
	return indexCacheInputIdentities{
		exact:         hex.EncodeToString(digest.Sum(nil)),
		dependency:    hex.EncodeToString(dependencyDigest.Sum(nil)),
		sourceFiles:   rootFileDigests,
		packageFiles:  allFileDigests,
		inputFiles:    inputFiles,
		goEnvironment: environmentValues,
	}, true, nil
}

// indexCacheGoEnvironment records the effective Go command environment instead of assuming process variables include go env -w settings.
func indexCacheGoEnvironment(ctx context.Context, root string) ([]byte, map[string]string, error) {
	command := exec.CommandContext(ctx, "go", "env", "-json")
	command.Dir = root
	output, err := command.Output()
	if err != nil {
		return nil, nil, err
	}
	values := map[string]string{}
	if err := json.Unmarshal(output, &values); err != nil {
		return nil, nil, err
	}
	// GOGCCFLAGS contains a fresh temporary build directory on every invocation;
	// its semantic inputs are already represented by the explicit compiler and CGO fields.
	delete(values, "GOGCCFLAGS")
	canonical, err := json.Marshal(values)
	if err != nil {
		return nil, nil, err
	}
	return canonical, values, nil
}

// indexCacheModuleRoots adds local replacement modules because their source can change without touching the main module's go.sum.
func indexCacheModuleRoots(root string, moduleFile *modfile.File) ([]string, bool) {
	roots := []string{filepath.Clean(root)}
	seen := map[string]struct{}{filepath.Clean(root): {}}
	for _, replacement := range moduleFile.Replace {
		if replacement == nil || replacement.New.Version != "" {
			continue
		}
		candidate := replacement.New.Path
		if !filepath.IsAbs(candidate) {
			candidate = filepath.Join(root, candidate)
		}
		absolute, err := filepath.Abs(candidate)
		if err != nil {
			return nil, false
		}
		absolute = filepath.Clean(absolute)
		info, err := os.Stat(filepath.Join(absolute, "go.mod"))
		if err != nil || !info.Mode().IsRegular() {
			return nil, false
		}
		if _, exists := seen[absolute]; exists {
			continue
		}
		seen[absolute] = struct{}{}
		roots = append(roots, absolute)
	}
	sort.Strings(roots)
	return roots, true
}

// indexCacheSourcePaths follows the indexer's source-tree boundaries while including non-Go files that can affect local package types.
func indexCacheSourcePaths(ctx context.Context, root string) ([]string, error) {
	paths := make([]string, 0, 128)
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if contextErr := ctx.Err(); contextErr != nil {
			return contextErr
		}
		if walkErr != nil {
			return walkErr
		}
		if path != root && sourceDirectoryIgnored(entry.Name()) {
			if entry.IsDir() {
				return filepath.SkipDir
			}
			if entry.Type()&fs.ModeSymlink != 0 {
				info, infoErr := os.Stat(path)
				if infoErr != nil {
					return infoErr
				}
				if info.IsDir() {
					return nil
				}
			}
		}
		covered, coverageErr := indexCacheSourceEntryCovered(path, entry)
		if coverageErr != nil {
			return coverageErr
		}
		if !covered {
			return errIndexCacheSourceTreeNotCovered
		}
		if entry.IsDir() {
			if path == root {
				return nil
			}
			_, moduleErr := os.Stat(filepath.Join(path, "go.mod"))
			if moduleErr == nil {
				return filepath.SkipDir
			}
			if !os.IsNotExist(moduleErr) {
				return moduleErr
			}
			return nil
		}
		name := entry.Name()
		if strings.HasSuffix(name, "_test.go") || !indexCacheSourceExtension(filepath.Ext(name)) {
			return nil
		}
		paths = append(paths, filepath.Clean(path))
		return nil
	})
	return paths, err
}

// indexCacheSourceExtension includes the source forms the Go command may use to derive package declarations and compiled types.
func indexCacheSourceExtension(extension string) bool {
	switch extension {
	case ".go", ".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx", ".m", ".mm", ".s", ".S", ".f", ".F", ".for", ".f90", ".syso", ".swig", ".swigcxx":
		return true
	default:
		return false
	}
}

// indexCacheFileDigests reads independent files concurrently and returns their content hashes in lexical walk order.
func indexCacheFileDigests(ctx context.Context, paths []string) ([]indexCacheFileDigest, error) {
	digests := make([]indexCacheFileDigest, len(paths))
	workerCount := min(runtime.GOMAXPROCS(0), maxSourceParserWorkers, len(paths))
	if workerCount == 0 {
		return digests, nil
	}
	jobs := make(chan int)
	errorsByIndex := make([]error, len(paths))
	var workers sync.WaitGroup
	workers.Add(workerCount)
	for range workerCount {
		go func() {
			defer workers.Done()
			for index := range jobs {
				if ctx.Err() != nil {
					continue
				}
				data, err := os.ReadFile(paths[index])
				if err != nil {
					errorsByIndex[index] = err
					continue
				}
				digests[index] = indexCacheFileDigest{
					path:     filepath.Clean(paths[index]),
					data:     data,
					sum:      sha256.Sum256(data),
					metadata: readIndexCacheSourceMetadata(paths[index], data),
				}
			}
		}()
	}
	for index := range paths {
		if ctx.Err() != nil {
			break
		}
		jobs <- index
	}
	close(jobs)
	workers.Wait()
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	for index, err := range errorsByIndex {
		if err != nil {
			return nil, fmt.Errorf("hash API index input %q: %w", paths[index], err)
		}
	}
	return digests, nil
}

// readIndexCacheInputFile retains one optional input exactly as it appeared when the generation fingerprint was formed.
func readIndexCacheInputFile(path string) (indexCacheInputFile, error) {
	input := indexCacheInputFile{path: filepath.Clean(path)}
	data, err := os.ReadFile(input.path)
	if os.IsNotExist(err) {
		return input, nil
	}
	if err != nil {
		return indexCacheInputFile{}, err
	}
	input.data = data
	input.present = true
	return input, nil
}

// writeIndexCacheInputFileState distinguishes missing optional inputs from exact snapshotted bytes without rereading the filesystem.
func writeIndexCacheInputFileState(digest hash.Hash, input indexCacheInputFile) {
	writeIndexCacheHashString(digest, input.path)
	if !input.present {
		writeIndexCacheHashString(digest, "missing")
		return
	}
	writeIndexCacheHashString(digest, "present")
	writeIndexCacheHashBytes(digest, input.data)
}

// writeIndexCacheHashString length-prefixes values so distinct path and option sequences cannot collide by concatenation.
func writeIndexCacheHashString(digest hash.Hash, value string) {
	writeIndexCacheHashBytes(digest, []byte(value))
}

// writeIndexCacheHashBytes writes a fixed-width length before each payload to retain unambiguous fingerprint framing.
func writeIndexCacheHashBytes(digest hash.Hash, value []byte) {
	var length [8]byte
	binary.BigEndian.PutUint64(length[:], uint64(len(value)))
	_, _ = digest.Write(length[:])
	_, _ = digest.Write(value)
}

// normalizedIndexCacheCompositionPath keeps equivalent relative spellings on one option identity.
func normalizedIndexCacheCompositionPath(root string, compositionPath string) string {
	resolved := resolvedIndexCacheCompositionPath(root, compositionPath)
	if resolved == "" {
		return ""
	}
	relative, err := filepath.Rel(root, resolved)
	if err == nil && relative != ".." && !strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return filepath.ToSlash(relative)
	}
	return filepath.Clean(resolved)
}

// resolvedIndexCacheCompositionPath resolves an explicit composition file against the same root used by route scoping.
func resolvedIndexCacheCompositionPath(root string, compositionPath string) string {
	if strings.TrimSpace(compositionPath) == "" {
		return ""
	}
	if !filepath.IsAbs(compositionPath) {
		compositionPath = filepath.Join(root, compositionPath)
	}
	absolute, err := filepath.Abs(compositionPath)
	if err != nil {
		return filepath.Clean(compositionPath)
	}
	return filepath.Clean(absolute)
}
