package webindex

import (
	"bytes"
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// stabilityHelperRootEnv passes an isolated checkout to subprocesses without making generated artifacts root-dependent.
const stabilityHelperRootEnv = "WEBINDEX_STABILITY_HELPER_ROOT"

// TestRunArtifactsAreStableAcrossCheckoutRoots verifies source paths and temporary directory names cannot perturb generated bytes.
func TestRunArtifactsAreStableAcrossCheckoutRoots(t *testing.T) {
	first := writeStabilityFixture(t)
	second := writeStabilityFixture(t)

	firstArtifacts := runStabilityFixture(t, first)
	secondArtifacts := runStabilityFixture(t, second)
	for name, firstContents := range firstArtifacts {
		if !bytes.Equal(firstContents, secondArtifacts[name]) {
			t.Fatalf("artifact %s differs across checkout roots\nfirst:\n%s\nsecond:\n%s", name, firstContents, secondArtifacts[name])
		}
	}
}

// TestRunArtifactsIgnoreUnrelatedSourceAdditions verifies adding a non-route package cannot renumber or rename existing API contracts.
func TestRunArtifactsIgnoreUnrelatedSourceAdditions(t *testing.T) {
	root := writeStabilityFixture(t)
	before := runStabilityFixture(t, root)
	writeFixtureFiles(t, root, map[string]string{
		"internal/unrelated/models.go": `package unrelated
type Record struct { Value string ` + "`json:\"value\"`" + ` }
func Helper() Record { return Record{} }
`,
	})
	after := runStabilityFixture(t, root)
	for name, beforeContents := range before {
		if !bytes.Equal(beforeContents, after[name]) {
			t.Fatalf("artifact %s changed after unrelated source addition\nbefore:\n%s\nafter:\n%s", name, beforeContents, after[name])
		}
	}
}

// TestRunArtifactsAreStableAcrossProcesses verifies randomized runtime map seeds cannot change artifact bytes.
func TestRunArtifactsAreStableAcrossProcesses(t *testing.T) {
	root := writeStabilityFixture(t)
	first := runStabilitySubprocess(t, root)
	second := runStabilitySubprocess(t, root)
	for name, firstContents := range first {
		if !bytes.Equal(firstContents, second[name]) {
			t.Fatalf("artifact %s differs across processes\nfirst:\n%s\nsecond:\n%s", name, firstContents, second[name])
		}
	}
}

// TestRunStabilitySubprocessHelper provides an isolated process entrypoint without shipping a separate fixture binary.
func TestRunStabilitySubprocessHelper(t *testing.T) {
	root := os.Getenv(stabilityHelperRootEnv)
	if root == "" {
		t.Skip("subprocess helper")
	}
	runStabilityFixture(t, root)
}

// writeStabilityFixture creates a native-context route with no machine-specific metadata.
func writeStabilityFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	writeFixtureFiles(t, root, map[string]string{
		"go.mod": "module example.com/stable\n\ngo 1.25\n",
		".env":   "APP_NAME=Stable API\n",
		"internal/health/controller.go": `package health
import (
	"net/http"
	"github.com/goforj/web"
)
type Controller struct{}
func (c *Controller) Routes() []web.Route {
	return []web.Route{web.NewRoute(http.MethodGet, "/health/:probe", c.Show)}
}
// Show reports health for one probe.
func (c *Controller) Show(ctx web.Context) error {
	_ = ctx.Param("probe")
	return ctx.NoContent(http.StatusNoContent)
}
`,
	})
	return root
}

// runStabilityFixture returns each generated artifact keyed by its stable basename.
func runStabilityFixture(t *testing.T, root string) map[string][]byte {
	t.Helper()
	buildDir := filepath.Join(root, "build")
	paths := map[string]string{
		"api_index.json":             filepath.Join(buildDir, "api_index.json"),
		"api_index.diagnostics.json": filepath.Join(buildDir, "api_index.diagnostics.json"),
		"openapi.json":               filepath.Join(buildDir, "openapi.json"),
	}
	if _, err := Run(context.Background(), IndexOptions{
		Root:            root,
		OutPath:         paths["api_index.json"],
		DiagnosticsPath: paths["api_index.diagnostics.json"],
		OpenAPIPath:     paths["openapi.json"],
	}); err != nil {
		t.Fatalf("run stability fixture: %v", err)
	}
	artifacts := make(map[string][]byte, len(paths))
	for name, path := range paths {
		contents, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read stability artifact %s: %v", name, err)
		}
		artifacts[name] = contents
	}
	return artifacts
}

// runStabilitySubprocess executes the same checked-in test binary with a fresh Go runtime and returns its artifacts.
func runStabilitySubprocess(t *testing.T, root string) map[string][]byte {
	t.Helper()
	executable, err := os.Executable()
	if err != nil {
		t.Fatalf("resolve webindex test executable: %v", err)
	}
	command := exec.Command(executable, "-test.run=^TestRunStabilitySubprocessHelper$", "-test.count=1")
	command.Env = append(os.Environ(), stabilityHelperRootEnv+"="+root)
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("run stability subprocess: %v\n%s", err, output)
	}
	return readStabilityArtifacts(t, root)
}

// readStabilityArtifacts reads a completed generation without running the index in the parent process.
func readStabilityArtifacts(t *testing.T, root string) map[string][]byte {
	t.Helper()
	buildDir := filepath.Join(root, "build")
	paths := map[string]string{
		"api_index.json":             filepath.Join(buildDir, "api_index.json"),
		"api_index.diagnostics.json": filepath.Join(buildDir, "api_index.diagnostics.json"),
		"openapi.json":               filepath.Join(buildDir, "openapi.json"),
	}
	artifacts := make(map[string][]byte, len(paths))
	for name, path := range paths {
		contents, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read subprocess stability artifact %s: %v", name, err)
		}
		artifacts[name] = contents
	}
	return artifacts
}
